version: '2.1'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:1.13.6
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  
  jaeger:
    image: jaegertracing/all-in-one:1.20.0
    command: ["--log-level=debug"]
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  opentelemetry_collector:
    image: otel/opentelemetry-collector:0.18.0
    command: ["--config=/etc/otel-collector-config.yaml", "--log-level=debug"]
    depends_on:
      - jaeger
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "55681:55681"

