version: '2.1'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:1.13.6
    container_name: dynamodb-local
    ports:
      - "29713:8000"
  
  jaeger:
    image: jaegertracing/all-in-one:1.20.0
    command: ["--log-level=debug"]
    ports:
      - "29798:6831/udp"
      - "29797:16686"
      - "29796:14268"
      - "29795:14250"

  opentelemetry_collector:
    image: otel/opentelemetry-collector:0.18.0
    command: ["--config=/etc/otel-collector-config.yaml", "--log-level=debug"]
    depends_on:
      - jaeger
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "29799:55681"

  profile_mock_server:
    image: stoplight/prism:4
    command: -p 29712 mock --host 0.0.0.0 "/etc/connect-profile-openapi.yml"
    volumes:
      - ./connect-profile-openapi.yml:/etc/connect-profile-openapi.yml
    ports:
      - "29712:29712"

