receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:55681"

processors:
  batch:
  queued_retry:

exporters:
  logging:
  jaeger:
    endpoint: "jaeger:14250"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [logging, jaeger]
