= Connect Account


== Setup

Before being able to start the project locally, you should have a way to run `Node.js` applications.

We recommend you to install the latest version of `asdf` to do so.

You will need `nodejs` and `yarn`.
These can be installed via the provided `.tool-versions` using `asdf install`.


Get required environment variables by copying `.env.sample` and if necessary tuning it to values relevant to your dev environment:

[source, shell]
----
cp .env_vars.sample .env_vars
----

Source the file to get variables defined your environnement:

[source, shell]
----
source .env_vars
----

== Development Process

[source, shell]
----
NODE_TLS_REJECT_UNAUTHORIZED=0 yarn dev
----

If you want to build and start the app, you should run the following:

[source, shell]
----
yarn build && yarn start -p $CONNECT_ACCOUNT_PORT
----

The `yarn start` port is not set by default, as it is used by Vercel for building the app.

== Testing

[source, shell]
----
yarn test
----

== Environment variables

|===
| Name | Description

| `CONNECT_ACCOUNT_PORT`
| Local port used to run the application.

| `CONNECT_ACCOUNT_SESSION_SALT`
| The password used to seal or access the cookie session. It needs to be at least 32 characters long. 

| `CONNECT_MANAGEMENT_URL`
| URL used to fetch identities from the management GraphQL endpoint.

| `CONNECT_MANAGEMENT_API_KEY`
| API key used to access the management GraphQL endpoint.

| `CONNECT_PROVIDER_URL`
| URL used to start the connect oauth flow.

| `CONNECT_APPLICATION_CLIENT_ID`
| Client ID of the online service (e.g. internet website, application) that uses the Provider Authentication and Authorization service for its User.

| `CONNECT_APPLICATION_CLIENT_SECRET`
| Paired with the client ID, used to authenticate the Application from which the User intent to sign in.

| `CONNECT_APPLICATION_SCOPES`
| Represents the kind of user authorized information and actions that an Application is able to access on another Application.

| `NEXT_PUBLIC_SENTRY_DSN`
| Data Source Name representing the configuration required by the Sentry SDKs.
|===


== Connect login implementation

To understand the flow of `connect-account`, you should read the `connect` https://developers.fewlines.co/guides/authorization_code_flow/overview/[documentation].


== Source Code Organization

We are using the NextJS folder architecture (i.e. `/pages`) to utilize its router, out of the box. For more information, please refer to the https://nextjs.org/docs/basic-features/pages[documentation].

We are also using the `Command Query Responsibility Segregation`(CQRS) pattern to separate queries from mutations. They are located in the `queries/` and `command/` folder.

=== /.github

- */workflows*: GitHub Actions used to run tests during CI/CD process flow.
- *PULL_REQUEST_TEMPLATE*: Template used when opening a pull request on GitHub.

=== /src

- *@types/*: Type declaration used in multiple places.
- *assets/*: Folder containing assets.
- *commands/*: Write (e.g. `POST`) database actions.
- *components/*: React components.
- *design-system/*: Style or atomic components (e.g. icons) related code.
- *hooks/*: Reusable actions flows.
- *middleware/*: Reusable wrappers to add various features to server side actions.
- *pages/*: NextJS router.
- *queries/*: Read (i.e. `GET`) database actions.
- *utils/*: Small snippets/functions used multiple times throughout the application
- *config.ts*: Entry point used to verify env vars sourcing, and prevent the app to run if forgotten.

=== /tests
- *__mocks__*: Centralized mocked data or function.
- **.test.(ts|tsx)*: Unit test files.

=== config files
- *package.json*: We use this file, as much as possible as a centralized config file for various packages, like `ESLint`, `Jest` or `Husky`.
- *tsconfig.json*: TypeScript compiler options.
- *next.config.js*: Extended webpack compiler config used by NextJS.

== Linting

We use a set of strict linting rules through `TypeScript` and `ESLint`. While `TypeScript` config is pretty standard, the `ESLint` one is mostly set with our own custom package, called https://www.npmjs.com/package/@fewlines/eslint-config[@fewlines/eslint-config]. You should read the documentation if you want the full power of the config while using `VSCode`.

> Note that, contrary to `errors`, `warnings` do not break testing or app compilation.

You can manually lint, using:

[source, shell]
----
yarn lint
----

or

[source, shell]
----
yarn lint --fix
----

if you want to automatically fix linting issues.

== Pre-push trigger

We are using `Husky` to trigger the linting, testing and building of the app before pushing the code to GitHub to prevent unnecessary `Vercel` build.

== TypeScript

=== Type declaration

The rule we follow is that, if a declared type is only used in one file, we locate it in said file. Otherwise, we move it in its own file, under `@types/`.
The exceptions to this rule are:

- *next-env.d.ts*: Adds NextJS types globally.
- *assets.d.ts*: Allow the import of assets files in TypeScript files.

as NextJS required them to be located at the root of the repository.

=== Typing React components

We chose to type React component like so:

[source, typescript]
----
import React from "react";

// Without props.
export const Foo: React.FC = () => { return ;}

// With props.
type BarProps = { foo: "bar" }

export const Bar: React.FC<BarProps> = ({ foo }) => { return <div>{ foo }</div>}
----

If you are not familiar with TypeScript generic types, please take a look at the https://www.typescriptlang.org/docs/handbook/generics.html[documentation].

== Style

=== Global style

The `globalStyle` object, found in `/src/design-system/globals/globalStyle.tsx`, is used to remove undesired style and behavior found in HTML. 

> Note that we chose to set the global font size to *62.5%*. This font size means that '1rem' is exactly equal to '10px', which makes setting REM values very simple.

The `globalStyle` is scoped in the `_app` page component.

=== Theme

You should prioritize theme values over arbitrary CSS values.

The theme structure is defined inside the `src/@types/styled-component.d.ts` definition type file.

The theme values are set inside `src/design-system/theme/lightTheme.ts` file. Each field are set individually, then assigned to the `lightTheme` variable.

The theme access is scoped in the `_app` page component.

You can access the theme properties and values inside a `styled` component by calling the `theme` props:

[source, typescript]
----
import styled from "styled-components";

// Note that styled component are PascalCase.
const StyledComponent = styled.div`
  css-property: ${({ theme }) => theme.themeKey};
`
----

You can access the theme properties and values from everywhere else with the custom `useTheme` hook:

[source, typescript]
----
import { useTheme } from "relative/path/to/the/hook";

const theme = useTheme();
----

To access our breakpoint definitions, you can import the `breakpointDevices` object from the theme file and apply the wanted breakpoint with the `@media` keyword:

[source, typescript]
----
import { deviceBreakpoints } from "relative/path/to/the/theme";

const StyledComponent = styled.div {
  @media ${deviceBreakpoints.xs} {}

  @media ${deviceBreakpoints.s} {}

  @media ${deviceBreakpoints.m} {}

  @media ${deviceBreakpoints.l} {}
}
----

Our chosen viewport breakpoints are : `576px` | `768px` | `992` | `1200`.

Sometimes, you want to pass custom props to your styled component. Here is the way to do it:

[source, typescript]
----
type StyledButtonProps = { isActive: boolean };

const StyledComponent = styled.button<StyledButtonProps>`
  ${({ isActive, theme }) => `color: ${isActive ? theme.green : theme.grey}`};
`;
----

=== SVG

If you want to use SVGs in your application, we recommend to render them as a React component, instead of importing the file:

[source, jsx]
----
import React from 'react'

export const SvgIcon: React.FC = () => {
  return (
    <svg>
      ...
    </svg>
  )
}
----
