version: "2.1"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "9411:9411"