/**
 * Connect Profile
 * The application stores user profile information, it is meant to be compliant to OpenID Connect specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineResponse422 {
    /**
    * an english message describing the error
    */
    'message'?: InlineResponse422MessageEnum;
    /**
    * an object representing invalid fields
    */
    'errors'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "InlineResponse422MessageEnum",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse422.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type InlineResponse422MessageEnum = "There is already a user with this sub in database" | "InvalidData" ;

