version: 2.1
jobs:
  lint-and-tests:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Launching Profile mock server
          command: docker-compose up -d profile_mock_server
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
          environment:
            CONNECT_PROFILE_URL: "http://localhost:29712"

  lighthouse:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: lighthouse reports
          command: |
            wget https://raw.githubusercontent.com/jfrazelle/dotfiles/master/etc/docker/seccomp/chrome.json -O ~/chrome.json
            docker run --rm --name perf \
            -e CONNECT_TEST_ACCOUNT_EMAIL=$CONNECT_TEST_ACCOUNT_EMAIL \
            -e CONNECT_TEST_ACCOUNT_PASSWORD=$CONNECT_TEST_ACCOUNT_PASSWORD \
            -e CONNECT_TEST_ACCOUNT_URL=$CONNECT_TEST_ACCOUNT_URL \
            -v $(pwd)/lighthouse-reports:/tmp/chrome/reports -v $(pwd)/bin:/home/chrome/testcases \
            --security-opt seccomp=$HOME/chrome.json \
            femtopixel/google-lighthouse-puppeteer e2e/lighthouse-report \
            -d /tmp/chrome/reports
            cat /home/chrome/reports/summary.json
      - store_artifacts:
          path: /tmp/chrome/reports/summary.json

workflows:
  CI:
    jobs:
      - lint-and-tests
      - lighthouse
