version: 2.1
orbs:
  docker: circleci/docker@1.6.0
jobs:
  linter:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          name: lint
          command: | 
            yarn install
            yarn lint
  integration-tests:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - docker/install-docker-compose
      - run:
          name: yarn-install
          command: yarn install
      - run:
          name: docker-compose-up
          command: docker-compose up -d profile_mock_server
      - run:
          name: run-test
          command: yarn test
          environment:
            CONNECT_PROFILE_URL: "http://localhost:29712"

workflows:
  lint-and-test:
    jobs:
      - linter
      - integration-tests
