version: 2.1

parameters:
  deployed_on_heroku:
    type: boolean
    default: false
  target_url:
    type: string
    default: ""

commands: 
  install-dependencies:
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
jobs:
  lint-and-tests:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    steps:
      - checkout
      - install-dependencies
      - run:
          name: "Lauching Profile mock server"
          command: docker-compose up -d profile_mock_server
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
          environment:
            CONNECT_PROFILE_URL: "http://localhost:29712"

  e2e-tests:
    docker: 
      image: buildkite/puppeteer:8.0.0
    steps: 
      - checkout
      - install-dependencies
      - run:
          name: Creating test user
          command: yarn e2e:create-test-user
          environment:
            CONNECT_TEST_ACCOUNT_EMAIL: "taiko@e2e.test"
            CONNECT_TEST_ACCOUNT_PASSWORD: $CONNECT_TEST_ACCOUNT_PASSWORD
            CONNECT_MANAGEMENT_URL: https://management.connect.review.fewlines.tech/graphql
            CONNECT_MANAGEMENT_API_KEY: $CONNECT_MANAGEMENT_API_KEY
      - run:
          name: Run e2e tests
          command: yarn test:e2e 
          environment:
            CONNECT_TEST_ACCOUNT_EMAIL: 'taiko_${CIRCLE_SHA1}@e2e.test'
            CONNECT_TEST_ACCOUNT_PASSWORD: $CONNECT_TEST_ACCOUNT_PASSWORD
            CONNECT_TEST_ACCOUNT_URL: << pipeline.parameters.target_url >>
      - run: 
          name: Removing test user
          command: yarn e2e:remove-test-user
          when: always
          environment:
            CONNECT_TEST_ACCOUNT_EMAIL: "taiko@e2e.test"
            CONNECT_MANAGEMENT_URL: https://management.connect.review.fewlines.tech/graphql
            CONNECT_MANAGEMENT_API_KEY: $CONNECT_MANAGEMENT_API_KEY

workflows:
  tests-on-push:
    when:
      not: << pipeline.parameters.deployed_on_heroku >>
    jobs:
      - lint-and-tests
  e2e-tests-after-heroku-deploy:
    when: << pipeline.parameters.deployed_on_heroku >>
    jobs: 
      - e2e-tests