version: 2.1

parameters:
  deployed_on_heroku:
    type: boolean
    default: false
  target_url:
    type: string
    default: ""
  is_staging_env:
    type: boolean
    default: true

commands: 
  install-dependencies:
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  lint-and-tests:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    steps:
      - install-dependencies
      - run:
          name: "Launching Profile mock server"
          command: docker-compose up -d profile_mock_server
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
          environment:
            CONNECT_PROFILE_URL: "http://localhost:29712"

  e2e-tests:
    docker: 
      - image: buildkite/puppeteer:8.0.0
    environment:
      CONNECT_TEST_ACCOUNT_URL: << pipeline.parameters.target_url >>
    steps: 
      - install-dependencies
      - run:
          name: Creating test user
          command: echo "export CONNECT_TEST_ACCOUNT_SUB=$(yarn e2e:create-test-user | xargs | cut -d' ' -f7 | cut -c-36)" >> $BASH_ENV
      - run: 
          name: Setting Profile staging URL env var
          command: echo "export CONNECT_PROFILE_URL=https://fewlines-profile-staging.herokuapp.com/" >> $BASH_ENV
          when: << pipeline.parameters.is_staging_env >>
      - run:
          name: Run e2e tests
          command: CONNECT_TEST_ACCOUNT_EMAIL="taiko_${CIRCLE_SHA1}@fewlines.test" yarn test:e2e 
      - run: 
          name: Cleaning Profile Staging
          command: yarn e2e:cleaning-profile-staging
          when: << pipeline.parameters.is_staging_env >> 
      - run: 
          name: Removing Connect test user
          command: yarn e2e:remove-test-user
          when: always

workflows:
  tests-on-push:
    when:
      not: << pipeline.parameters.deployed_on_heroku >>
    jobs:
      - lint-and-tests
  e2e-tests-after-heroku-deploy:
    when: << pipeline.parameters.deployed_on_heroku >>
    jobs: 
      - e2e-tests
