version: 2.1
jobs:
  lint-and-tests:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Launching Profile mock server
          command: docker-compose up -d profile_mock_server
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
          environment:
            CONNECT_PROFILE_URL: "http://localhost:29712"

  lighthouse:
    docker:
      - image: fewlines/docker-lighthouse-puppeteer:CU-ht6h0f_35aca8af5105
        environment:
          CHROME_FLAGS: "--headless --disable-gpu --no-sandbox --disable-setuid-sandbox"
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: lighthouse reports
          command: |
            pwd && lighthouse-puppeteer -c "--headless --disable-gpu --no-sandbox --disable-setuid-sandbox" /root/project/bin/e2e/lighthouse-report.js

workflows:
  CI:
    jobs:
      - lint-and-tests
      - lighthouse
