version: 2.1
jobs:
  lint-and-tests:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Launching Profile mock server
          command: docker-compose up -d profile_mock_server
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
          environment:
            CONNECT_PROFILE_URL: "http://localhost:29712"
  
  lighthouse:
    docker:
      - image: cimg/node:14.17.0-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Connect.Account dependencies
          command: yarn install
      - run:
          name: Install Puppeteer
          command: yarn add -D puppeteer
      - save_cache:
          name: Save Yarn Package Cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run Lighthouse audit
          command: npx @lhci/cli autorun
      - store_artifacts:
          path: ./lhci_reports

workflows:
  CI:
    jobs:
      - lint-and-tests
      - lighthouse
