version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    default_reviewers:
      - "Fuzznimp"
      - "Oluane"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "express"
          version_requirement: "5.x"
