name: CI e2e test - Render

on:
  pull_request:
    
jobs:
  e2e-tests-render: 
    runs-on: ubuntu-latest

    container:
      image:  node:14.8-buster

    env:
      GITHUB_CONTEXT_EVENT: ${{ toJson(github.event) }}

    steps:
    - uses: actions/checkout@v2

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: adding Render PR preview URL to Application's redirect uris
      env:
        CONNECT_ACCOUNT_TEST_APP_ID: ${{ secrets.CONNECT_ACCOUNT_TEST_APP_ID }}
        CONNECT_MANAGEMENT_URL: ${{ secrets.CONNECT_MANAGEMENT_URL }}
        CONNECT_MANAGEMENT_API_KEY: ${{ secrets.CONNECT_MANAGEMENT_API_KEY }}
      run: yarn e2e:add-render-redirect-uri
