name: CI e2e

on:
  deployment_status:
    
jobs:
  e2e-tests: 
    runs-on: ubuntu-latest

    container:
      image:  node:14.8-buster

    # services:
    #   taiko:
    #     image: fewlines/taiko:0.1.0
    #     volumes:
    #       - /tests/e2e:/app/tests
    
    steps:
    - uses: actions/checkout@v2

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: docker installation
      run: |
        apt-get update 
        apt install -y apt-transport-https ca-certificates curl software-properties-common gnupg2
        curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
        apt update
        apt-get install -y docker-ce
    
    - name: dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: adding Vercel URL to Application's redirect uris
      env:
        GITHUB_CONTEXT_EVENT: ${{ toJson(github.event) }}
        CONNECT_ACCOUNT_TEST_APP_ID: ${{ secrets.CONNECT_ACCOUNT_TEST_APP_ID }}
        CONNECT_MANAGEMENT_URL: ${{ secrets.CONNECT_MANAGEMENT_URL }}
        CONNECT_MANAGEMENT_API_KEY: ${{ secrets.CONNECT_MANAGEMENT_API_KEY }}
      run: yarn e2e-add-redirect-uri

    - name: tests
      run: |
        echo $PWD
        ls $PWD/tests/e2e
        ps -p $$
    
    - name: lauching taiko e2e tests
      if: github.event.deployment_status.state == 'success'
      env: 
        GITHUB_CONTEXT_EVENT: ${{ toJson(github.event) }}
        CONNECT_ACCOUNT_TEST_EMAIL: ${{ secrets.CONNECT_ACCOUNT_TEST_EMAIL }}
        CONNECT_ACCOUNT_TEST_PASSWORD: ${{ secrets.CONNECT_ACCOUNT_TEST_PASSWORD }}
        CONNECT_ACCOUNT_TEST_URL: ${{ github.event.deployment_status.target_url }}
      run: | 
        docker run --volume $(pwd)/tests/e2e:/app/__tests__:ro \
        --env CONNECT_ACCOUNT_TEST_EMAIL=$CONNECT_ACCOUNT_TEST_EMAIL \
        --env CONNECT_ACCOUNT_TEST_PASSWORD=$CONNECT_ACCOUNT_TEST_PASSWORD \
        --env CONNECT_ACCOUNT_TEST_URL=$CONNECT_ACCOUNT_TEST_URL \
        fewlines/taiko:0.1.0 \
        docker volume ls
