name: CI

on:
  push:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fewlines/account-puppeteer:0.0.1
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
    
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      puppeteer:
        image: fewlines/mongo-with-replica-set:4.4.1
        ports:
          - 27017:27017

