name: CI e2e test

on:
  deployment_status:

jobs:
  e2e-tests:
    if: ${{ contains(github.event.deployment_status.target_url, 'heroku') && github.event.deployment_status.state == 'success'}}
    runs-on: ubuntu-latest

    container:
      image: buildkite/puppeteer:8.0.0

    env:
      GITHUB_CONTEXT_EVENT: ${{ toJson(github.event) }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2.1.6
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: taiko
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn add -D taiko

      - name: creating test user
        env:
          CONNECT_TEST_ACCOUNT_EMAIL: "taiko@e2e.test"
          CONNECT_TEST_ACCOUNT_PASSWORD: ${{ secrets.CONNECT_TEST_ACCOUNT_PASSWORD }}
          CONNECT_MANAGEMENT_URL: ${{ secrets.CONNECT_MANAGEMENT_URL }}
          CONNECT_MANAGEMENT_API_KEY: ${{ secrets.CONNECT_MANAGEMENT_API_KEY }}
        run: yarn e2e:create-test-user

      - name: e2e
        run: yarn test:e2e
        env:
          CONNECT_TEST_ACCOUNT_EMAIL: 'taiko_${{ github.event.deployment.sha }}@e2e.test'
          CONNECT_TEST_ACCOUNT_PASSWORD: ${{ secrets.CONNECT_TEST_ACCOUNT_PASSWORD }}
          CONNECT_TEST_ACCOUNT_URL: ${{ github.event.deployment.payload.web_url }}

      - name: removing test user
        if: ${{ always() }}
        env:
          CONNECT_TEST_ACCOUNT_EMAIL: "taiko@e2e.test"
          CONNECT_MANAGEMENT_URL: ${{ secrets.CONNECT_MANAGEMENT_URL }}
          CONNECT_MANAGEMENT_API_KEY: ${{ secrets.CONNECT_MANAGEMENT_API_KEY }}
        run: yarn e2e:remove-test-user

  trigger-circle-ci-e2e-tests:
    if: ${{ contains(github.event.deployment_status.target_url, 'heroku') && github.event.deployment_status.state == 'success'}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set branch name
        id: set-branch-name
        run: |
          if [[ "${{github.event.deployment.environment}}" == "fewlines-account-staging" ]]; then
            echo "::set-output name=branch_name::main"
          fi
          if [[ !("${{github.event.deployment.environment}}" == "fewlines-account-production") && !("${{github.event.deployment.environment}}" == "fewlines-account-staging") ]]; then
            git describe --all ${{ github.sha }} | cut -d/ -f3- | xargs -I '{}' echo "::set-output name=branch_name::{}"
          fi

      - name: Trigger Circle Ci pipeline
        run: |
          curl -f --request POST \
            --url https://circleci.com/api/v2/project/github/fewlinesco/connect-account/pipeline \
            --header 'Circle-Token: ${{ secrets.CIRCLE_CI_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
            "branch": "${{ steps.set-branch-name.outputs.branch_name }}",
            "parameters": {
              "deployed_on_heroku": true,
              "target_url": "${{ github.event.deployment.payload.web_url }}"
            }
          }'
