name: CI e2e test

on:
  deployment_status:

jobs:
  e2e-tests:
    if: ${{ contains(github.event.deployment_status.target_url, 'heroku') && github.event.deployment_status.state == 'success'}}
    runs-on: ubuntu-latest

    container:
      image: buildkite/puppeteer:8.0.0

    env:
      GITHUB_CONTEXT_EVENT: ${{ toJson(github.event) }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2.1.6
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: creating test user
        id: test-user-creation
        env:
          CONNECT_TEST_ACCOUNT_EMAIL: "taiko@e2e.test"
          CONNECT_TEST_ACCOUNT_PASSWORD: ${{ secrets.CONNECT_TEST_ACCOUNT_PASSWORD }}
          CONNECT_MANAGEMENT_URL: ${{ secrets.CONNECT_MANAGEMENT_URL }}
          CONNECT_MANAGEMENT_API_KEY: ${{ secrets.CONNECT_MANAGEMENT_API_KEY }}
        run: echo "::set-output name=test-user-sub::$(yarn e2e:create-test-user | xargs | cut -d' ' -f7 | cut -c-36)"

      - name: e2e
        run: yarn test:e2e
        env:
          CONNECT_TEST_ACCOUNT_EMAIL: 'taiko_${{ github.event.deployment.sha }}@e2e.test'
          CONNECT_TEST_ACCOUNT_PASSWORD: ${{ secrets.CONNECT_TEST_ACCOUNT_PASSWORD }}
          CONNECT_TEST_ACCOUNT_URL: ${{ github.event.deployment.payload.web_url }}
          CONNECT_PROFILE_URL: ${{ secrets.CONNECT_PROFILE_URL }}
          CONNECT_TEST_USER_SUB: ${{ steps.test-user-creation.outputs.test-user-sub }}

      - name: cleaning profile staging
        # if: ${{ github.event.deployment_status.state == 'success' && success()  }}
        run: yarn e2e:cleaning-profile-staging
        env:
          CONNECT_TEST_USER_SUB: ${{ steps.test-user-creation.outputs.test-user-sub }}
          CONNECT_PROFILE_STAGING_API_KEY: ${{ secrets.CONNECT_PROFILE_STAGING_API_KEY }}
          CONNECT_PROFILE_URL: ${{ secrets.CONNECT_PROFILE_URL }}

      - name: removing test user
        if: ${{ always() }}
        env:
          CONNECT_TEST_ACCOUNT_EMAIL: "taiko@e2e.test"
          CONNECT_MANAGEMENT_URL: ${{ secrets.CONNECT_MANAGEMENT_URL }}
          CONNECT_MANAGEMENT_API_KEY: ${{ secrets.CONNECT_MANAGEMENT_API_KEY }}
        run: yarn e2e:remove-test-user
      