name: CI

on:
  push:
    
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: dependencies
      run: yarn install

    - name: linter
      run: yarn lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: dependencies
      run: yarn install

    - name: linter
      run: yarn test
